AWSTemplateFormatVersion: '2010-09-09'
Description: LaLiga Companion Tool


Resources:
  LaLigaFunction:
    Type: AWS::Serverless::Function
    Properties:
      # runtime and handler do not need to be specified for
      # image-based functions, but Code must contain the URI of a
      # container image in the ECR registry
      FunctionName: LaLiga
      MemorySize: 512
      Timeout: 180
      Runtime: python3.8
      PackageType: Image
      ImageConfig:
        Command: ["main.hourly_handler"]
      Code:
        ImageUri: 129276784352.dkr.ecr.eu-west-1.amazonaws.com/laliga:master-cb5103dad4caad4a117ff650a3854a10d762da03
      # Events:
      #   LaLiga:
      #     Type: Api
      #     Properties:
      #       Path: /hello
      #       Method: get
    # Metadata:
    #   DockerTag: laliga.latest
    #   DockerContext: ./
    #   Dockerfile: Dockerfile


# Outputs:
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for LaLiga function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/hello/"
